name: Build image
on:
  push:
    branches:
      - master

jobs:
# JOB to run change detection
changes:
  runs-on: ubuntu-latest
  # Set job outputs to values from filter step
  outputs:
    check-changes: ${{ steps.filter.outputs.check-changes }}
  steps:
  # For pull requests it's not necessary to checkout the code
  - uses: dorny/paths-filter@v2
    id: filter
    with:
      filters: |
        check-changes:
          - 'builder/**''
          - 'scripts/**'
          - 'focal-rt-ros2/**'
          - 'Makefile'
  build-image:
    needs: changes
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.check-changes == 'true' }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup build dependencies
        run: .github/workflows/setup-dependencies.sh

      - name: Build image
        run: .github/workflows/build.sh

      # TODO: release, but the file is really big (8GB)
